### ISSUE TITLE
DeleteMany and ForceDeleteMany won't accept slice of entities 

### ISSUE THREAD

**Issue by farhadhf** [latolukasz/beeorm#11]
The [documentation](https://beeorm.io/guide/crud.html#deleting-entities) sample code for DeleteMany is 
```go
var products []*ProductEntity
engine.LoadByIDs(int64{1, 2}, &products)
engine.DeleteMany(products...)
```
But the following code won't compile, saying `Cannot use 'requestEntities' (type []*entity.UserEntity) as the type []Entity`:
```go
ormService := service.DI().OrmEngine().Clone()
var requestEntities []*entity.UserEntity
ormService.Search(beeorm.NewWhere("CreatedAt < DATE_ADD(UTC_TIMESTAMP(), INTERVAL -30 DAY)"), nil, &requestEntities)
ormService.DeleteMany(requestEntities...)
```

The workaround is to pass the entities to `DeleteMany` one by one:
```go
for _, requestEntity := range requestEntities {
	ormService.DeleteMany(requestEntity)
}
```

Am I missing something or is the documentation wrong?

**Comment by latolukasz** [comment]
Hi @farhadhf , i see i had bug in my documentation. Now documentation is fixed.
This code:
```go
var products []*ProductEntity
engine.LoadByIDs(int64{1, 2}, &products)
engine.DeleteMany(products...)
```

was wrong.


I created new version https://github.com/latolukasz/beeorm/releases/tag/v1.14.0 where all ...Many() methods are removed. You should use methods without Many suffix.

In your scenario you should use flusher:
```go
ormService := service.DI().OrmEngine().Clone()
var requestEntities []*entity.UserEntity
ormService.Search(beeorm.NewWhere("CreatedAt < DATE_ADD(UTC_TIMESTAMP(), INTERVAL -30 DAY)"), nil, &requestEntities)

flusher := ormService.NewFlusher()
for _, e := range requestEntities {
    flusher.Delete(e)
}
flusher.Flush()
```
