### ISSUE TITLE
Consider using prepared statements in BeeORM

### ISSUE THREAD

**Issue by mycroftcanner** [latolukasz/beeorm#12]
Title: Consider using prepared statements in BeeORM

I just finished reading the BeeORM documentation and it looks great! I'm excited to try it in my project.

However, I noticed in the documentation that "While BeeORM allows batch queries, it also greatly increases the risk of SQL injections. Be sure you are always validating and escaping values used in batch query. Especially string values provided by application users (from web form for instance). You can use tools.EscapeSQLParam() method to escape string values..."

Prepared statements are generally considered more robust and secure than manually escaping values, as they use placeholders for user-provided input rather than incorporating the input directly into the query. The `tools.EscapeSQLParam()` method doesn't seem very robust in comparison.

One solution could be to add support for prepared statements in BeeORM, allowing users to take advantage of the increased security and performance benefits of prepared statements when executing batch queries. This could be done by adding a new method or interface for preparing and executing prepared statements, similar to the way it is done in other database drivers.

As the Go documentation [mentions](https://go.dev/doc/database/prepared-statements), prepared statements can help prevent SQL injection attacks. They work by separating the SQL code from the parameter values, forcing the developer to define the SQL code first and then pass in the parameter values separately. This separation helps prevent the entire SQL command from being constructed incorrectly and being vulnerable to injection attacks.

In Go, the `database/sql` package's `DB.Prepare` method returns a `Stmt` value representing a prepared statement. The returned `Stmt` is bound to a connection and can be used until the connection is closed or the statement is destroyed by calling its `Close` method. The `Stmt.Exec` and `Stmt.Query` methods can be used to execute the statement with different parameter values.

**Comment by latolukasz** [comment]
Hi @mycroftcanner 

Thanks for your input. I was planning to add support for prepared statements (i know them very well) in BeeORM. I will look into it next days.

I will keep you updated.

**Comment by latolukasz** [comment]
Added in version 2.2.0:

https://beeorm.io/guide/mysql_queries.html#prepared-statements
