### ISSUE TITLE
Add support for Bloom filters in BeeORM's Redis stream functionality

### ISSUE THREAD

**Issue by mycroftcanner** [latolukasz/beeorm#13]
I recently started using BeeORM and I love how easy it is to work with Redis streams. The `engine.GetEventBroker().NewFlusher().Publish(stream, event)` method is particularly convenient for publishing events to Redis streams.

I have a use case where it would be really helpful to have the option to skip adding items to the stream if they already exist, using a Bloom filter. I have included a Lua script that demonstrates how this can be done, as well as an example of how it can be used in Go code.

In my implementation, I have a `Add` method that takes in a field and a value to be added to a stream, as well as a flag for whether the item should be checked for uniqueness. If the `uniq` flag is set to `true`, the method calls a Lua script to add the item to the stream and check for uniqueness in a Bloom filter. If the item already exists in the Bloom filter, it is not added to the stream.

If the `uniq` flag is set to `false`, the item is added to the stream without checking for uniqueness.

To handle the case where an item is not added to the stream because it already exists in the Bloom filter, I have a second stream called `dupeKey` that stores potential duplicates. I then have a separate process that consumes this stream and checks if the items stored in it are actually duplicates or not.

It would be great if BeeORM could add support for using Bloom filters to skip adding items that already exist in Redis streams. This would allow users to more easily prevent duplicates in their streams and improve the performance of their applications.

Thank you for considering this feature request!

```go
// Add adds a new entry to the stream.
// If uniq is true, it only adds the entry if it doesn't already exist in the stream.
// If uniq is false, it adds the entry regardless of whether it already exists or not.
func (s *stream) Add(ctx context.Context, field, value string, uniq bool) (bool, error) {
	key := s.key

	// Call the xaddUnique Lua script to add the field and value to the stream
	// and check for uniqueness in the bloom filter.
	if uniq {
		var err error
		uniq, err = xaddUnique.Exec(
			ctx,
			s.client,
			[]string{key, s.bloomKey},
			[]string{field, value},
		).AsBool()
		if err != nil || uniq || s.dupeKey == "" {
			return uniq, err
		}

		// Use the dupeKey and fallthrough
		// the condition to store the duplicate value.
		key = s.dupeKey
	}

	// Add the new entry to the stream without checking for uniqueness.
	return uniq, s.client.Do(
		ctx,
		s.client.B().Xadd().Key(key).Id("*").FieldValue().FieldValue(field, value).Build(),
	).Error()
}
```

lua script:

```lua
-- LUA_XADD_UNIQ is a Lua script that adds a field and value to a Redis stream, and
-- adds an item to a Redis Bloom filter to track the field and value. It takes in two
-- keys, representing the stream and the Bloom filter, and two arguments, representing
-- the field and value to be added.

-- The script first constructs an item by concatenating the stream key, the field,
-- and the value. It then checks if the item already exists in the Bloom filter using
-- the BF.EXISTS command. If the item exists, the script returns false without adding
-- the item to the stream or the Bloom filter.

-- If the item does not exist in the Bloom filter, the script adds the item to the
-- stream using the XADD command, and then adds the item to the Bloom filter using the
-- BF.ADD command. It then returns true to indicate that the item was successfully
-- added to the stream and the Bloom filter.

local key = KEYS[1]
local bloom = KEYS[2]
local field = ARGV[1]
local value = ARGV[2]
local item = key .. ":" .. field .. ":" .. value

-- Check if the item already exists in the bloom filter
local success, result = pcall(redis.call, "BF.EXISTS", bloom, item)
if not success then
  return result.err
elseif result == 1 then
  return false
end

-- Add to the stream
local success, result = pcall(redis.call, "XADD", key, "*", field, value)
if not success then
  return result.err
end

-- Add to the bloom filter
local success, result = pcall(redis.call, "BF.ADD", bloom, item)
if not success then
  return result.err
end

return true
```

**Comment by latolukasz** [comment]
Hi @mycroftcanner, love the idea. i will do it next days

**Comment by latolukasz** [comment]
Hi @mycroftcanner

I decided to implement new version of BeeORM/V3 which is developed from scratch. This time i focused on memory performance trying to reduce memory allocations to minimum. I managed also to increase performance more than 10 times in most operations. In this version i am not supporting my own custom implementation of redis streams, that's why i am closing this issue.
