### ISSUE TITLE
no way to specify SentinelPassword in RegisterRedisSentinelWithCredentials

### ISSUE THREAD

**Issue by andrius4669** [latolukasz/beeorm#9]
Currently, `RegisterRedisSentinelWithCredentials` allows setting only `redis.FailoverOptions.Password`, and not `redis.FailoverOptions.SentinelPassword`.
I understand that changing API surface of `RegisterRedisSentinelWithCredentials` for this would be breaking change, so something like `RegisterRedisSentinelWithOptions` could be introduced instead.

Also, our current deployments use password without user, so
```
	if user != "" {
		options.Username = user
		options.Password = password
	}
```
isn't helpful (why check at all, when defaults are empty strings anyway, so assigning empty string would be no-op).

**Comment by andrius4669** [comment]
something like
```
func (r *Registry) RegisterRedisSentinelWithOptions(namespace string, opts redis.FailoverOptions, db int, sentinels []string, code ...string) {
	opts.DB = db
	opts.SentinelAddrs = sentinels
	if opts.MaxConnAge == 0 {
		opts.MaxConnAge = time.Minute * 2
	}
	client := redis.NewFailoverClient(&opts)
	r.registerRedis(client, code, fmt.Sprintf("%v", sentinels), namespace, db)
}
```
could work?

**Comment by latolukasz** [comment]
I am gonna fix it toda

**Comment by latolukasz** [comment]
Thanks @andrius4669 for your great ideas, i used your method in beeorm registry. Also issue with redis user and password is fixed.

I need to enable github issues notifications. Next time i am gonna fix new issues the same day.

Best
Lukasz

**Comment by andrius4669** [comment]
thanks
